### ISSUE TITLE
Need to put a description of REST API addon on the plugin page.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wpem-rest-api#10]
Need to put a description of the REST API addon on the plugin page.

![image](https://user-images.githubusercontent.com/35419531/104992758-b58c9800-5a47-11eb-9ea0-edbb755bd2b6.png)

**Comment by hiteshmakvana** [comment]
@krinaydhanani Please assign the content related bug to a particular department.

**Comment by Prachetshi1991** [comment]
Lets users connect the Mobile application with their WordPress events website.

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1ogbyk9xJilt8i7P6uak2_1HyjJoNUxLFioWrId3Kf-A/edit
