### ISSUE TITLE
Remove option b from below mentioned screenshot

### ISSUE THREAD

**Issue by jathinkj** [wpeventmanager/wpem-rest-api#103]
https://wp-eventmanager.com/knowledge-base/rest-api/
![image](https://github.com/wpeventmanager/wpem-rest-api/assets/144658262/fd4871c2-5cf3-48c5-9240-880ca03f95aa)

**Comment by Prachetshi1991** [comment]
I am not the right person for this job... @shoyeb can handle this

**Comment by wpemmarketing** [comment]
Removed option B.
