### ISSUE TITLE
PHP 8.2 Deprecated code error

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#107]
Deprecated: Creation of dynamic property WPEM_Rest_API_Settings::$settings_group is deprecated in D:\xampp\htdocs\eventlist\wp-content\plugins\wpem-rest-api\admin\wpem-rest-api-settings.php on line 17

Deprecated: Creation of dynamic property WPEM_Rest_API_Admin::$settings_page is deprecated in D:\xampp\htdocs\eventlist\wp-content\plugins\wpem-rest-api\admin\wpem-rest-api-admin.php on line 21

Deprecated: Creation of dynamic property WP_Event_Manager_Alerts::$post_types is deprecated in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager-alerts/wp-event-manager-alerts.php on line 88

Deprecated: Creation of dynamic property WPEM_Registrations::$post_types is deprecated in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager-registrations/wp-event-manager-registrations.php on line 96

Deprecated: Creation of dynamic property WP_Event_Manager_Settings::$settings_group is deprecated in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager/admin/wp-event-manager-settings.php on line 21

Deprecated: Creation of dynamic property WP_Event_Manager_Admin::$settings_page is deprecated in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager/admin/wp-event-manager-admin.php on line 29

**Comment by DevByDoll** [comment]
What is your php version ?

**Comment by mistry-jignesh** [comment]
I have verified issue. Now Deprecated code error is fixed.
Now this error message is not available .
So I closed the issue.

**Comment by mistry-jignesh** [comment]
I have verified this issue . Still facing a Deprecated error is available on the page.

![image](https://github.com/wpeventmanager/wpem-rest-api/assets/75515088/fd999be4-466d-4cd0-9491-734800004488)

**Comment by ritakikani** [comment]
@mistry-jignesh  Code review done from my side.

**Comment by mistry-jignesh** [comment]
I have verified issue. Now Deprecated code error is fixed.
So I closed the issue.
