### ISSUE TITLE
In the mobile app status is not change 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#113]
From the web application change the status checked in to check-in then in the mobile app status is not changed.

![image](https://github.com/user-attachments/assets/dfdd6a3a-6c51-466c-89cf-2521ef7894d3)

**Comment by officialnishantdhiman** [comment]
@mistry-jignesh This is working fine.

**Comment by mistry-jignesh** [comment]
I have verified this issue. In the app attendee status is proper.
It is working fine. So I closed the issue.
