### ISSUE TITLE
Ticket sales : Report is not dispaly 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#115]
Ticket sales : Report is not display

**Comment by mistry-jignesh** [comment]
![image](https://github.com/user-attachments/assets/57d42081-dbf9-4e25-ac81-40ae2900a806)

**Comment by ritakikani** [comment]
https://github.com/wpeventmanager/wp-event-manager-sell-tickets/issues/481

**Comment by mistry-jignesh** [comment]
This issue is fixed in the sell ticket addon.
So I closed the issue.
