### ISSUE TITLE
Repeated ajax requests sending while selecting color. 

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wpem-rest-api#12]
Repeated ajax requests sending while selecting a colour. 

![image](https://user-images.githubusercontent.com/35419531/105837901-5b667680-5ff5-11eb-8902-c834e07a3bf9.png)

**Comment by hiteshmakvana** [comment]
There is no any other solution. 

.wpColorPicker() only provide change event to call ajax.

Next update we will improve this.

**Comment by mistry-jignesh** [comment]
I have verified this issue. Still facing the same issue.

![image](https://github.com/wpeventmanager/wpem-rest-api/assets/75515088/ae0830f1-0383-4507-bb9d-6835eeb0c7fa)

**Comment by iamakram22** [comment]
@mistry-jignesh Please verify again, now the Ajax is only sent when the user selects the color. Previously the Ajax request was sent continuously while dragging the cursor in color picker.

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now when I drag and drop the button then Ajax requests is sent.

So I closed the issue.
