### ISSUE TITLE
Need to provide image size description. 

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wpem-rest-api#14]
Need to provide image size description so the user can upload perfect size logo which is not cropped in the app. 

![image](https://user-images.githubusercontent.com/35419531/105842445-332e4600-5ffc-11eb-8b60-8d0e9c7b4a85.png)

**Comment by hiteshmakvana** [comment]
@krinaydhanani Ask satadal or @siddharthgotawala  to provide image details.

**Comment by jrsarath** [comment]
No need of this as app doesnt stores images it loads directly

**Comment by mistry-jignesh** [comment]
As per @jrsarath  - No need of this as app doesnt stores images it loads directly.

So I closed the issue
