### ISSUE TITLE
Need to show the save message while saving App Branding.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wpem-rest-api#15]
Need to show the save message while saving App Branding.

@Priya-Goenka Please provide suitable text for the notice. 

![image](https://user-images.githubusercontent.com/35419531/105981392-080b2b80-60bc-11eb-88bf-3d62e295e0a3.png)

**Comment by krinaydhanani** [comment]
@hiteshmakvana Please check it once.

![image](https://user-images.githubusercontent.com/35419531/106245709-ebddca80-6232-11eb-8672-06f9316e6a73.png)

**Comment by hiteshmakvana** [comment]
Successfully save App Branding.

**Comment by Prachetshi1991** [comment]
You have successfully saved your preferred color for your app branding. 
or 
Your preferred color for your app branding has been successfully saved.

**Comment by iamakram22** [comment]
1. 
![image](https://github.com/wpeventmanager/wpem-rest-api/assets/55661376/259969d6-f11e-4bd0-b814-6e300d3b4fa9)

2. 
![image](https://github.com/wpeventmanager/wpem-rest-api/assets/55661376/61e38c66-b5eb-4cbd-ab13-a990b7a05b75)

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now a message is available while App branding is saved.
So I closed the issue.
