### ISSUE TITLE
Need to fix a design issue in REST API. 

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wpem-rest-api#16]
Please show the notice in proper alignment. 

![image](https://user-images.githubusercontent.com/35419531/106245136-ffd4fc80-6231-11eb-91d6-2f1641b77d91.png)

**Comment by hiteshmakvana** [comment]
In the next release, we can improve design things.

**Comment by iamakram22** [comment]
Issue fixed now

![image](https://github.com/wpeventmanager/wpem-rest-api/assets/55661376/26a84276-70a4-48c8-b79a-eb13f5fbe97b)

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this design issue is fixed.
So I closed the issue.
