### ISSUE TITLE
Need to fix the multiple notice issue.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wpem-rest-api#17]
**1. The issue in APP Branding.**

![image](https://user-images.githubusercontent.com/35419531/106245709-ebddca80-6232-11eb-8672-06f9316e6a73.png)

![image](https://user-images.githubusercontent.com/35419531/106250192-51cd5080-6239-11eb-8e6e-d1a7482bd843.png)

**2. The issue in API Access.**

![image](https://user-images.githubusercontent.com/35419531/106250594-df10a500-6239-11eb-92d4-09ee28bbff92.png)

**3. The issue in General Settings.**

I am not getting any save successfully message.

**Comment by krinaydhanani** [comment]
3. The issue in General Settings.

I am not getting any save successfully message.

This issue was still remains.

**Comment by mistry-jignesh** [comment]
Still above all issue are not resolve.
