### ISSUE TITLE
Need to Fix  - Post Attendee note issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#20]
When I have try to add note using post option .Here Attendee is not available and When I pass random number for attendee then

note is created.  Which is wrong .

URL - https://staging-appwpeventmanager.temp927.kinsta.cloud/wp-json/wpem/events/23/attendees/4000001/notes?note=hello..Hello&status=new

Please check it.

![image](https://user-images.githubusercontent.com/75515088/107478536-a52b9100-6b9f-11eb-96b5-632052d2cad2.png)

**Comment by jrsarath** [comment]
fixed at wpeventmanager/wp-event-manager-registrations@318dd100ae3e07e5eb642c265953e5ea3e7b4f49

**Comment by mistry-jignesh** [comment]
I have verified issue. When I pass random number for attendee then note is not created. 

This issue is fixed and working fine.

So I closed the issue.
