### ISSUE TITLE
Need to fix - Get tickets and Get Order issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#21]
When I have use wrong event id and valid ticket id  and click on the send button then tickets is get on the page.

Please correct it.

URL : https://staging-appwpeventmanager.temp927.kinsta.cloud/wp-json/wpem/events/33/tickets/147

![image](https://user-images.githubusercontent.com/75515088/107482101-410bcb80-6ba5-11eb-9ed7-889d65a7c8d4.png)

Same issue I have face in the **Get Order**  . Please check image.

URL : https://staging-appwpeventmanager.temp927.kinsta.cloud/wp-json/wpem/events/33/orders/421

![image](https://user-images.githubusercontent.com/75515088/107486887-921ebe00-6bab-11eb-990b-66f1934d1a95.png)

**Comment by jrsarath** [comment]
fixed in wpeventmanager/wp-event-manager-sell-tickets@34364a6055a8f6fdaee864a67719f489783155b7

**Comment by mistry-jignesh** [comment]
I have verified issue . This issue is fixeed .

When I have use wrong event id and valid ticket id then proper message is display.

So I closed the issue.
