### ISSUE TITLE
Need to fix - Group issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#22]
I have use event id which is not available in the event list . This event id is working properly in the below image in the group option .

![image](https://user-images.githubusercontent.com/75515088/107501924-082c2080-6bbe-11eb-9d4d-757e92caf226.png)

URL - https://staging-appwpeventmanager.temp927.kinsta.cloud/wp-json/wpem/events/31/groups/7

In above url event id "31" is not available but this event id is working properly. Please check image.

![image](https://user-images.githubusercontent.com/75515088/107502189-60fbb900-6bbe-11eb-8957-77db0b5ddc54.png)

Same issue face in  Get Group issue.

Also When I have use valid group id and invalid event is and perform Delete operation then group is delete .

Please check it.

**Comment by mistry-jignesh** [comment]
I have verified issue. If enter invalid event id then result is search .

![image](https://user-images.githubusercontent.com/75515088/153170901-fb06612b-0a5d-4b89-a37d-ce51673662f6.png)

If I have enter event id is different not related to group id then also result is search.

![image](https://user-images.githubusercontent.com/75515088/153173400-d985fa12-bc40-4c86-895b-8aa98e3c3669.png)

**Comment by jrsarath** [comment]
![image](https://user-images.githubusercontent.com/29149814/153174588-29dd102d-3403-4e8b-8be2-3c611924760d.png)
![image](https://user-images.githubusercontent.com/29149814/153174775-4355687f-ec32-444b-9058-e0decf93c6ba.png)
update plugins properly

**Comment by mistry-jignesh** [comment]
I have verified issue . This issue is working fine.

May be issue is occured due to cache.

So now I closed the issue.
