### ISSUE TITLE
Need to fix - Guest Put issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#23]
1. When I have update guest information then information is updated but in the message email address field is display blank.  

![image](https://user-images.githubusercontent.com/75515088/107512534-fb62f900-6bcc-11eb-9dca-406fd6da8b88.png)

2. Also Guest Get issue : 
   
 When I have run below URL  then name and address field are display blank. 

https://staging-appwpeventmanager.temp927.kinsta.cloud/wp-json/wpem/events/54/groups/16/guests/563

![image](https://user-images.githubusercontent.com/75515088/108816612-7cae8880-75dc-11eb-85f6-2c306f2ce49d.png)

**Comment by kinjal6810** [comment]
update
![image](https://user-images.githubusercontent.com/104058202/177158485-82565d19-8aca-4375-9383-54c9888b5ba7.png)

**Comment by kinjal6810** [comment]
Request to u transfer this bug Guestlist plugin.

**Comment by mistry-jignesh** [comment]
https://github.com/wpeventmanager/wpem-guests/issues/89

I have created this issue in the guest plugin. So I closed the issue.
