### ISSUE TITLE
Need to fix -  Report option issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#26]
1.When I have use **date_min** then it is showing not proper result .

https://staging-appwpeventmanager.temp927.kinsta.cloud/wp-json/wpem/reports/sales?event_id=23&period=month&date_min=2021-02-03 

2.When I have use **date_max** then it is showing not proper result  . 

https://staging-appwpeventmanager.temp927.kinsta.cloud/wp-json/wpem/reports/sales?event_id=23&period=month&date_min=2021-02-10 

3.When I have use **group by** then it is showing not proper result . With any option.

https://staging-appwpeventmanager.temp927.kinsta.cloud/wp-json/wpem/reports/sales?event_id=23&period=month&date_min=2021-02-03&grouped_by=week

![image](https://user-images.githubusercontent.com/75515088/107604365-fa29de80-6c55-11eb-90fb-29bb363895d7.png)

4. When I have pass invalid event id then display result on the screen.

https://staging-appwpeventmanager.temp927.kinsta.cloud/wp-json/wpem/reports/sales?event_id=121&period=last_month&grouped_by=week

![image](https://user-images.githubusercontent.com/75515088/108826883-efbefb80-75ea-11eb-9990-c8d9e0a03140.png)

**Comment by iamakram22** [comment]
This is **Sell Ticket Addon** issue, assigned to Rita after having a discussion

**Comment by mistry-jignesh** [comment]
This issue is created in the sell ticket.
So I closed the issue.
