### ISSUE TITLE
Need to fix - Get event issue 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#28]
When I have enter wrong event id then it will display the search result.

When I use wrong id then proper message should come on the screen.

![image](https://user-images.githubusercontent.com/75515088/107608209-4cbcc800-6c61-11eb-87b5-d589dd65cd39.png)

Same issue I have face in **"Get Attendee"** .

![image](https://user-images.githubusercontent.com/75515088/107609029-b63dd600-6c63-11eb-84d3-8ab189d4d5af.png)

**Comment by jrsarath** [comment]
We have backend function to truncate extra stuffs, 000 before an number means no value so its gets automatically truncated/trimmed at backend while retrieving events or attendees,

**Comment by mistry-jignesh** [comment]
As per @jrsarath - 000 before an number means no value so its gets automatically truncated/trimmed at backend while retrieving events or attendees.

So I closed the issue.
