### ISSUE TITLE
Need to fix - Put Attendee issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#29]
When I try to update attendee information then attendee information is not update.

URL - https://staging-appwpeventmanager.temp927.kinsta.cloud/wp-json/wpem/events/54/attendee/401?attendee_email=fastract02@email.com

![image](https://user-images.githubusercontent.com/75515088/107610807-82b17a80-6c68-11eb-8ee7-b2f99d8bd4e0.png)

**Also Post Attendee issue :** 

When I try to create new attendee using "Post" then new attendee is unable to create .

**Comment by kinjal6810** [comment]
![image](https://user-images.githubusercontent.com/104058202/176190103-fe4aff36-7e41-4ce8-a966-b139a51390fc.png)
Request to you check URL.

**Comment by mistry-jignesh** [comment]
Verified this issue but I have correct the URL but display the error message.

https://staging-appwpeventmanager.kinsta.cloud/wp-json/wpem/events/5329/attendees/5659?events_id=5329&attendees_id=5659&attendee_email=UserA4@gmail.com

![image](https://user-images.githubusercontent.com/75515088/177764035-ea9ee95c-d073-4efa-9120-3d24780b2547.png)

**Comment by kinjal6810** [comment]
There are not using update functionality so close this issue

**Comment by mistry-jignesh** [comment]
After discussed issue with @krinaydhanani . 

There are not using update functionality. 

So I close this issue .
