### ISSUE TITLE
Need to fix - Get Attendee issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#30]
When I have use valid event id and wrong attendee id then it is display below result . Please check image.

![image](https://user-images.githubusercontent.com/75515088/108496667-664cb800-72d0-11eb-879b-364d55b40cfa.png)

**Comment by jrsarath** [comment]
fixed in wpeventmanager/wp-event-manager-registrations@d3d2b7e6e498b684c7481d55035b2724fac04bd2

**Comment by mistry-jignesh** [comment]
I have verified issue . Issue is fixed.

Now display proper message on the screen.

So I closed the issue.
