### ISSUE TITLE
Need to fix event selection issue.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wpem-rest-api#31]
If and admin select only one event then in the APP we need to show only one event.

![image](https://user-images.githubusercontent.com/35419531/108692401-9095b400-7522-11eb-8d92-254f4a776458.png)

**Comment by krinaydhanani** [comment]
I can see user name rather than Event name.

**Comment by mistry-jignesh** [comment]
Right now event field is removed  and fixed the issue.

So now I have verified issue and closed the issue.
