### ISSUE TITLE
Need to fix the time issue.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wpem-rest-api#32]
Time is not working in Expiry date when I create a key. 

![image](https://user-images.githubusercontent.com/35419531/108957940-50584200-7698-11eb-8339-094d9040164d.png)

**Comment by mistry-jignesh** [comment]
Please correct box size.

![image](https://user-images.githubusercontent.com/75515088/109611872-ea1a6600-7b54-11eb-9537-33c9b67208a7.png)

**Comment by kaushikpokal** [comment]
It's common width in input, so it's proper
