### ISSUE TITLE
Need to provide copied key button on key generate page. 

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wpem-rest-api#36]
Need to provide copied key button on key generate page. 

1. The reason behind putting this button is we need to allow to a user click somewhere once they copied the keys. When he clicks on this page we need to redirect them to the API Access page. 
2. @siddharthgotawala Please put a copied icone end of the all keys box so the user can copy with just one click. 

![image](https://user-images.githubusercontent.com/35419531/108984257-b901e780-76b5-11eb-87be-3b40aaa08049.png)

**Comment by iamakram22** [comment]
1.
![image](https://github.com/wpeventmanager/wpem-rest-api/assets/55661376/3a90ac32-fa58-4447-a288-0805b97d8b6b)

2.
![image](https://github.com/wpeventmanager/wpem-rest-api/assets/55661376/27e09726-63e9-45d6-bbbf-6e56376ad950)

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is fixed.
Copied key button is available.

![image](https://github.com/wpeventmanager/wpem-rest-api/assets/75515088/17f5a83d-b524-47d8-a7c0-5b9692d879fa)

So I closed the issue.
