### ISSUE TITLE
Need to fix arrivals time issue.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wpem-rest-api#37]
Our API sends the wrong check-in time so in the arrivals section, it's showing wrong.

**Comment by hiteshmakvana** [comment]
QRCode checkin has time update issue in sell ticket API.

**Comment by mistry-jignesh** [comment]
This issue is verified . Now it is fixed.

**Comment by krinaydhanani** [comment]
Yes now, this issue was fixed. I am going to close this issue.
