### ISSUE TITLE
Need to fix - Put Event - Expiry status is not change

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#39]
When event is expiry and from postman I have changed end date,expiry date and deadline date .
 
Set above all date as future date. Here date is updated but event status is display as expiry.  

![image](https://user-images.githubusercontent.com/75515088/119219597-f4208500-bb03-11eb-8d88-495bac719e3b.png)

**Comment by jrsarath** [comment]
Needs hitesh help

**Comment by kinjal6810** [comment]
Now properly work.

**Comment by mistry-jignesh** [comment]
As per @kinjal6810 - We dont have this funcationaly.

Doesn't need to look at this issue.

So I closed the issue.
