### ISSUE TITLE
Need to fix - Attendee checkin and checkout issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#40]
When I used invalid event id and invalid attendee id then also in the message box display message "checkin successfully" .

Please change the message.

![image](https://user-images.githubusercontent.com/75515088/119222748-87ad8200-bb13-11eb-91d8-790652fbf244.png)

**Comment by jrsarath** [comment]
fixed in wpeventmanager/wp-event-manager-registrations@02da954a3a65dbff47116873aa538f0d4a2da317

**Comment by mistry-jignesh** [comment]
I have verified .

When I have used invaild id for event & attendee then proper message is display.

Now this issue is working fine.

So I closed the issue.
