### ISSUE TITLE
Need to fix - Post attendee note - created by name is display blank

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#41]
Post attendee note - created by name is display blank .

Please check image.

![image](https://user-images.githubusercontent.com/75515088/119222980-9ea0a400-bb14-11eb-8d6d-9eb40c411e59.png) 

![image](https://user-images.githubusercontent.com/75515088/119223069-f5a67900-bb14-11eb-8e53-418f1257055f.png)

**Comment by jrsarath** [comment]
https://github.com/wpeventmanager/wp-event-manager-registrations/commit/a3caeca4bf4e58d5c3f6f75084bf36837c00aa68 fixed

**Comment by mistry-jignesh** [comment]
I have verified issue. Now this issue is fixed.

Post attendee note - Created by name is display .

So I closed the issue.
