### ISSUE TITLE
Put Event - Unable to edit event details 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#42]
I have try edit event title and online event status .

Unable to edit event details .

https://staging-appwpeventmanager.temp927.kinsta.cloud/wp-json/wpem/events/3184?event_title=Indian Tools 2021&event_online=Yes

**Comment by jrsarath** [comment]
pass argument event_description instead of description
for sample check below
![image](https://user-images.githubusercontent.com/29149814/152930641-c5407664-b0ff-4703-861e-2ca163257587.png)

**Comment by mistry-jignesh** [comment]
I have verified issue as for just update with event title name & desctription.

Here title name & decription are not update.

![image](https://user-images.githubusercontent.com/75515088/153155097-0643cea1-ca5b-4532-8206-cc9b296459c6.png)

Here created new Draft event in the backend.

![image](https://user-images.githubusercontent.com/75515088/153155408-fc1e610c-e47f-4497-9378-19d837183433.png)

**Comment by jrsarath** [comment]
hmm thats weird 
i nned to discuss with hitesh

**Comment by tamanna-ahuja** [comment]
We dont have  this funcationaly anymore , Discussed with @krinaydhanani . Doesn't need to look at this issue

**Comment by mistry-jignesh** [comment]
As per @kinjal6810 - We dont have this funcationaly.

Doesn't need to look at this issue.

So I closed the issue.
