### ISSUE TITLE
Display the error message 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#44]
Display the error message .

![image](https://user-images.githubusercontent.com/75515088/134518389-533dfabc-4ae5-49f1-aaa9-38db16c33ff4.png)

**Comment by jrsarath** [comment]
fixed already

**Comment by mistry-jignesh** [comment]
I have verified issue .Now this issue fixed.

This issue is not facing in the admin dashboard. Now working fine.

So I closed the issue.
