### ISSUE TITLE
in guest list rest api takes a trash information 

### ISSUE THREAD

**Issue by yukta05** [wpeventmanager/wpem-rest-api#48]
deleted the guest from the backend side but still you can see it in mobile app 
 have to removing the guest from the trash,

**Comment by jrsarath** [comment]
fixed in @wpeventmanager/guests-lists commit 69246c41e6798fa7e2fdbba04ebf052aa1c553c2

**Comment by mistry-jignesh** [comment]
I have verified this issue. 

Deleted the guest from the backend side but still you can see it in mobile app issue is fixed.

Now this issue is working fine.

So I closed the issue.
