### ISSUE TITLE
Display the Fatal error message 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#49]
I have run below URL then fatal error is display.

**GET**

URL - https://staging-appwpeventmanager.temp927.kinsta.cloud/wp-json/wpem/events/4067

![image](https://user-images.githubusercontent.com/75515088/153180415-bbd4a4cb-e3b3-4f95-afe7-3f147b9b9c04.png)

**Comment by jrsarath** [comment]
Fixed in @017f9f539470fe2833abd67c907805bbdb7962f9

**Comment by mistry-jignesh** [comment]
I have verified issue. Now fatal error issue is fixed and working fine.

So I closed the issue.
