### ISSUE TITLE
Guest List- Mobile screen is display the white screen

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#51]
Created New group from the Web app.

I have added few guests in this group.

Now go to mobile app > Guest Lists

Click on the Guests.

Observed that on the mobile screen is display the white screen.

https://user-images.githubusercontent.com/75515088/153335044-c77d06a1-694b-4406-a677-21bb5c7bd29e.mp4

BackEND -  ![image](https://user-images.githubusercontent.com/75515088/153338155-84546fb4-e070-4d7b-abf4-f400dfcbf030.png)

![image](https://user-images.githubusercontent.com/75515088/153338231-44b8d68c-8c71-466d-82a4-79766c901cbc.png)

**Comment by jrsarath** [comment]
fixed in wpeventmanager/wpem-organizer-app@a5310692d1bd9408a58144b7877da81188f618ba
