### ISSUE TITLE
Delete Attendee notes - Note is deleted but display message - Undefined index

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#53]
Note is deleted but display  message - Undefined index.

I have run below URL -

https://staging-appwpeventmanager.temp927.kinsta.cloud/wp-json/wpem/events/3876/attendees/4491/notes?note_id=791&force=true

And display the display message - Undefined index.

![image](https://user-images.githubusercontent.com/75515088/153358666-540f4c63-3662-40b3-8c4d-0a34056af7d7.png)

**Comment by jrsarath** [comment]
Its not our issue, its kinsta's issue

**Comment by mistry-jignesh** [comment]
As per @jrsarath - Its kinsta's issue the notice is issued from kinsta's cache plugin.

This issue is not our plugin end. 

So I closed the issue.
