### ISSUE TITLE
After deleting attendee data from event then attendee data are availabel in the mobile 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#55]
Attendee tab - After deleting attendee data from event then attendee data are availabel in the mobile.

![image](https://user-images.githubusercontent.com/75515088/153566622-c8f5f1c0-30cd-459e-9ad5-e3968ad7864b.png)

![image](https://user-images.githubusercontent.com/75515088/153566665-1a07dcba-a2c8-4fe2-a065-67484e82bcfb.png)

**Comment by jrsarath** [comment]
fixed in wpeventmanager/wp-event-manager-registrations@8a278924a7f388a68123ecb06d1ecb7240eb5de4

**Comment by mistry-jignesh** [comment]
I have verified issue. Now this issue is fixed .

After deleting attendee data from event then attendee data are remove from the mobile.

Now this issue is working fine.

So I closed the issue.
