### ISSUE TITLE
Bug Reported.

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wpem-rest-api#56]
Also, just ran across a bug in your code. The Rest API plugin’s “General” settings where you can upload the “App Logo” the HTML code for the form has the “action” set like this:

 

action=""options.php""

 

See the two sets of double quotes? The form them won’t submit properly. The HTML should be just:

 

action="options.php"

**Comment by vijayrathod245** [comment]
It's working fine from my side

**Comment by mistry-jignesh** [comment]
Verified this issue. It is working fine .

![image](https://user-images.githubusercontent.com/75515088/178902506-727ecfba-947c-4ac8-b076-23dd0422eb4f.png)

The Rest API plugin’s “General” settings where you can upload the “App Logo” the HTML code for the form has the “action” set like this:

action="options.php"

So I closed the issue.
