### ISSUE TITLE
Attendess Section - Display message - There are no attendees

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#57]
Attendess Section - Display message - There are no attendees.

![image](https://user-images.githubusercontent.com/75515088/163568090-33f9a9f5-f842-4776-8a0c-9f916419ac90.png)

![image (18)](https://user-images.githubusercontent.com/75515088/163568026-6fb0d515-6ee2-46e1-9bd3-562aacb55fbf.png)

**Comment by tamanna-ahuja** [comment]
API is working check on staging , please find attached screenshot
![apiworking](https://user-images.githubusercontent.com/16346531/165504679-c80921a1-5ae3-4443-a0d8-511c356e41ec.PNG)

**Comment by mistry-jignesh** [comment]
I have verified issue in the rest api.In the rest api attendee run below url then it is working .

https://staging-appwpeventmanager.kinsta.cloud/wp-json/wpem/events/3427/attendees/

![image](https://user-images.githubusercontent.com/75515088/165682616-b242b07b-15c0-4d45-ab4a-34782fd7f8ae.png)

In the mobile app  -Attendess Section - Display message - There are no attendees.

**Comment by jrsarath** [comment]
Please test properly and assign to the appropriate person

**Comment by mistry-jignesh** [comment]
Verified issue . 

Now this issue is fixed . Attendee section - Attnendee are availabel.

So I closed the issue.
