### ISSUE TITLE
Need to remove Create an API key button from the API Access.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wpem-rest-api#6]
Need to remove the Create an API key button from the API Access because  Add Key and Create an API key both are working the same So there is no meaning to show both buttons.

![image](https://user-images.githubusercontent.com/35419531/97415438-7a545000-18c2-11eb-8aae-a01b6dae4932.png)

**Comment by hiteshmakvana** [comment]
This is needed @siddharthgotawala need to make better design and make button center and big. This will allow user to create API first time.

**Comment by siddharthgotawala** [comment]
Added image for reference for how it look.
![image](https://user-images.githubusercontent.com/68212017/107640982-071bf180-6c99-11eb-913e-b115103a5fc4.png)

**Comment by mistry-jignesh** [comment]
Please add button like below image

![image (3)](https://user-images.githubusercontent.com/75515088/108710313-e7f34e80-7539-11eb-960e-658511d47edf.png)

**Comment by mistry-jignesh** [comment]
This issue is fixed . Now it is working fine.

**Comment by krinaydhanani** [comment]
This issue was fixed. Now it's looking better than the previous.
