### ISSUE TITLE
App is not loading

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#69]
App is not loading.

u: eventmanager
p: gJaDwffi%Ljj*jEDYPLKK53E

URL - https://girlsrugbyclub.com/wp-admin

Key- 2165106979

**Comment by kinjal6810** [comment]
Priya, Tell this client update REST API plugin

**Comment by mistry-jignesh** [comment]
URL - https://girlsrugbyclub.com/wp-admin

Key- 2061966322
Key- 2023091197

Login in the app with above details. This App is laoding & Event is visible in the account.

So I closed the issue.
