### ISSUE TITLE
Message is display - Rest api unsupported

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#70]
Verified this issue.First I have login in the app and checked here rest api not supported message is display.

I have updated rest in their account and checked but same error message is display.

There are 2 our plugin availabel . One is wp event manager and registration.

![image](https://user-images.githubusercontent.com/75515088/171792040-a2ffd686-69dc-4428-9d5b-7d3a2ae120e5.png)

URL - https://www.retisonore.it/

Key - 3233287980

Same issue for other user.

https://nagato-germany.com/wp-admin/?wtlwp_token=8d549797ae624272b81725d4da95502b69394[…]1f9f70bca024eeca26a01482f69c8c07cb92b544f8b9746744024a06b0a

**Comment by ritakikani** [comment]
We need credential of adminpanel to identify the issue cause got html response in event listing api.

**Comment by ritakikani** [comment]
Uninstall app and then again install app with staging site, now issue is resolve.

**Comment by mistry-jignesh** [comment]
Verified this issue. First uninstalled the app from mobile and agian installed .

Now try to loign with valid key and URL.

Here Rest api unsupported message issue is fixed.

So I closed the issue.
