### ISSUE TITLE
Checkedin attendees not showing up.

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wpem-rest-api#74]
![image](https://user-images.githubusercontent.com/65893994/175863806-76063208-001f-443e-90f8-62a1234e3aed.png)
![image](https://user-images.githubusercontent.com/65893994/175863821-89918547-1381-4397-b105-ca87cf22d4b4.png)

**Comment by kinjal6810** [comment]
![Image from iOS (1)](https://user-images.githubusercontent.com/104058202/178469898-92dbc9b5-fb0c-4e7a-aa9d-0fe74d53c544.png)
display attendee the checked-in from my side

**Comment by kinjal6810** [comment]
Ask for credential if client issue

**Comment by mistry-jignesh** [comment]
Verified this issue. Checkedin attendees details are showing and working fine.

So I closed the issue.
