### ISSUE TITLE
Please check the issues reported by client. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wpem-rest-api#75]
- Custom logo is not appearing on the app
- Ticket Sells showing Not Avaliable 
- Order tab on mobile app not working 
- Always have to name the device, it doesn't save
https://staging35.eventik.com.au/

**Comment by ritakikani** [comment]
Order tab is working fine now.

Custom logo and ticket report is remaining to test and resolve.

For device name issue need to discuss with @krinaydhanani  @mistry-jignesh  @jrsarath @Priya-Goenka

**Comment by ritakikani** [comment]
After discuss , we decide that it is ok that if user signout and then logged in again then must need to add device name.

**Comment by ritakikani** [comment]
In rest api, custom logo is return but not display in device so this is problem in app side.


https://github.com/wpeventmanager/wpem-organizer-app/issues/414

**Comment by mistry-jignesh** [comment]
Verified this issue Order tab on mobile app not working . Now this issue is working.

Order are availabel in the order tab. 

So I closed the issue.
