### ISSUE TITLE
Error message is display WooCommerce -Setting page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#80]
Error message is display WooCommerce - Setting page -Tickets Fees.

![image](https://user-images.githubusercontent.com/75515088/183404284-be7f897d-dc2c-4752-9978-2cca5b789538.png)

**Comment by ritakikani** [comment]
This warning message is not from our side, it is because latest wordpress was not fully compitible with latest php so please use PHP 8.0.0 and wordpress 6.1.1and verify it again.

**Comment by mistry-jignesh** [comment]
As per @ritakikani - This warning message is not from our side, it is because latest wordpress was not fully compitible with latest php so please use PHP 8.0.0 and wordpress 6.1.1and verify it again.

![image](https://user-images.githubusercontent.com/75515088/208821280-d5d7df6f-7364-4565-bc35-3fa842ba4c99.png)

This error message is not face with latest version .

So I closed the issue.
