### ISSUE TITLE
Backend - License option -Asking for license key

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#83]
Rest API- Asking for license key.

This plugin is free . So need to remove field from backend.

![image](https://user-images.githubusercontent.com/75515088/195058920-87dfff90-20ea-4796-a734-2eaa662e2588.png)

**Comment by ritakikani** [comment]
This issue is resolve so please check again with all new addons.

**Comment by mistry-jignesh** [comment]
Verified this issue in the License option . Here Rest API option still display in the list.

This plugin is free . So need to remove field from backend.

![image](https://user-images.githubusercontent.com/75515088/206165324-58595e4d-3bc4-4969-b125-32b9e5e16224.png)

**Comment by ritakikani** [comment]
This issue is already resolve please take latest code with version 1.0.3 and verify again.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed and working fine.

Rest API option is remove from the list.

![image](https://user-images.githubusercontent.com/75515088/208820443-29e06531-7cc5-4e79-8c6a-94af3ccf73f3.png)

So I closed the issue.
