### ISSUE TITLE
App not getting data/connecting

### ISSUE THREAD

**Issue by SG-PR** [wpeventmanager/wpem-rest-api#84]
For the latest available version 1.2, the app is not connecting to the website.

In the logs we see:
83.84.111.218 - - [05/Dec/2022:10:36:38 +0100] "GET /wp-json/wpem-auth/appkey?key=xxxxxxxxxxxx HTTP/1.1" 302 - "-" "okhttp/4.9.1"
83.84.111.218 - - [05/Dec/2022:10:36:39 +0100] "GET /mijn-account/ HTTP/1.1" 200 12550 "-" "okhttp/4.9.1"
83.84.111.218 - - [05/Dec/2022:10:36:46 +0100] "GET /wp-json/wpem-auth/appkey?key=xxxxxxxxxxxx HTTP/1.1" 302 - "-" "okhttp/4.9.1"
83.84.111.218 - - [05/Dec/2022:10:36:46 +0100] "GET /mijn-account/ HTTP/1.1" 200 12550 "-" "okhttp/4.9.1"

(correct key replaced by xxxx here for security reasons)

The Rest-API plugin was installed but without a license key (we see there is no licens needed and in version 1.03 this is said to be fixed but version 1.03 does not seem to be available).

The only message we get from the app is "Something went wrong".

Any ideas on this?

Kind regards,

Peter
Sitegurus

**Comment by ritakikani** [comment]
hi @SG-PR ,

We had resolve all above issue with newer version of wpem-rest-api 1.0.3 and latest app.


Thank you.

**Comment by mistry-jignesh** [comment]
Verified this issue with new version 1.0.3 . Now this issue is fixed and working fine.
App is connected with device and not facing any error message.

**Comment by SG-PR** [comment]
> hi @SG-PR ,
> 
> We had resolve all above issue with newer version of wpem-rest-api 1.0.3 and latest app.
> 
> Thank you.

Hi @ritakikani 
Where can we download the release? The latest release seems to be 1.02: https://github.com/wpeventmanager/wpem-rest-api/releases

Also your company website is showing the plugin as missing: https://wp-eventmanager.com/product/rest-api/

Thank you,
kind regards,
Peter
Sitegurus
