### ISSUE TITLE
Event how to add image

### ISSUE THREAD

**Issue by patel-nimesh** [wpeventmanager/wpem-rest-api#87]
![image](https://user-images.githubusercontent.com/121149500/220028208-23ec128b-6fcd-437f-a48d-9e6abeba3e5b.png)

How to add image and how works?

**Comment by ritakikani** [comment]
We do not have this functionality in our app, so this api is not developed in our plugin.

**Comment by mistry-jignesh** [comment]
As per @ritakikani - We do not have this functionality in our app, so this API is not developed in our plugin.
So I closed the issue.
