### ISSUE TITLE
Need to fix the spalling capitalization issue. 

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wpem-rest-api#9]
Need to fix the spalling capitalization issue. 

WP Event Manager - Rest API --> **WP Event Manager - REST API**

![image](https://user-images.githubusercontent.com/35419531/104992586-65153a80-5a47-11eb-8ef8-8a6b4e476b6a.png)

**Comment by hiteshmakvana** [comment]
@Priya-Goenka Please confirm.

**Comment by krinaydhanani** [comment]
@hiteshmakvana I already confirm this issue with @ashokdudhat in the last meeting.

**Comment by mistry-jignesh** [comment]
Also Please change in at back end . Event manger - REST API 

![image](https://user-images.githubusercontent.com/75515088/108708865-01939680-7538-11eb-8ca6-3c9afa8a82cc.png)

**Comment by hiteshmakvana** [comment]
Its menu no need to change the text.

**Comment by krinaydhanani** [comment]
I disagree with this decision but according to @hiteshmakvana, the name is correct.
