### ISSUE TITLE
The installation process - For reset API

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#90]
The installation process - For reset API.

![image](https://github.com/wpeventmanager/wpem-rest-api/assets/75515088/bfa96328-f940-4b5b-8b1d-3211b70fa78a)

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1ogbyk9xJilt8i7P6uak2_1HyjJoNUxLFioWrId3Kf-A/edit

**Comment by mistry-jignesh** [comment]
Now content are added in the live site. So I closed the issue.
