### ISSUE TITLE
Explain General settings, API Access Settings ,App Branding setting 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#91]
All options should Explain in details :  General settings, API Access Settings, and App Branding settings.

![image](https://github.com/wpeventmanager/wpem-rest-api/assets/75515088/e4b7aaef-1dc2-4fc6-8717-f50fa896c312)

For Above all points covered in the URL:  https://wp-eventmanager.com/knowledge-base/mobile-app/

**Comment by Prachetshi1991** [comment]
https://docs.google.com/document/d/1ogbyk9xJilt8i7P6uak2_1HyjJoNUxLFioWrId3Kf-A/edit

**Comment by mistry-jignesh** [comment]
Now content are added in the live site. So I closed the issue.
